In [290]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [291]:
df = pd.read_excel("C:/Users/Ekangsh/OneDrive/Desktop/DS BootCamp/Datasets/flight_price.xlsx")

In [292]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [293]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]
df.drop('Date_of_Journey', axis = 1, inplace= True)

In [294]:
df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

In [295]:
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [296]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [297]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [298]:
df['Arrival_Hour'] = df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Minutes'] = df['Arrival_Time'].str.split(':').str[1]
df['Arrival_Hour'] = df['Arrival_Hour'].astype(int)
df['Arrival_Minutes'] = df['Arrival_Minutes'].astype(int)
df.drop('Arrival_Time', axis=1, inplace=True)

In [299]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [300]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hour     10683 non-null  int64
 13  Arrival_Minutes  10683 non-null  int64
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

In [301]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [302]:
df.isnull().sum()

Airline            0
Source             0
Destination        0
Route              1
Dep_Time           0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
Date               0
Month              0
Year               0
Arrival_Hour       0
Arrival_Minutes    0
dtype: int64

In [303]:
df[df['Route'].isnull()]

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes
9039,Air India,Delhi,Cochin,NaN,09:45,23h 40m,NaN,No info,7480,6,5,2019,9,25

In [304]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [305]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: object

In [306]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops': 2, '3 stops':3, '4 stops': 4, np.nan:1})

In [307]:
df

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,0,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,2h 30m,0,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,2h 35m,0,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,3h,0,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,2h 40m,0,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,8h 20m,2,No info,11753,9,5,2019,19,15

In [308]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10683 non-null  int64
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hour     10683 non-null  int64
 13  Arrival_Minutes  10683 non-null  int64
dtypes: int64(7), object(7)
memory usage: 1.1+ MB

In [309]:
df['Total_Stops'].value_counts()

Total_Stops
1    5626
0    3491
2    1520
3      45
4       1
Name: count, dtype: int64

In [310]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,0,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1,No info,13302,1,3,2019,21,35

In [311]:
df.drop('Route', axis=1, inplace=True)

In [312]:
df.head()

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,09:25,19h,2,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,No info,13302,1,3,2019,21,35

In [313]:
df['Duration_Hour']=df['Duration'].str.split(' ').str[0].str.split('h').str[0]

df['Duration_Minutes']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [314]:
df.head()

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Duration_Hour,Duration_Minutes
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,No info,3897,24,3,2019,1,10,2,50
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,No info,7662,1,5,2019,13,15,7,25
2,Jet Airways,Delhi,Cochin,09:25,19h,2,No info,13882,9,6,2019,4,25,19,NaN
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,No info,6218,12,5,2019,23,30,5,25
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,No info,13302,1,3,2019,21,35,4,45

In [315]:
df['Duration_Hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

In [316]:
df['Duration_Minutes'].unique()

array(['50', '25', nan, '45', '30', '5', '15', '35', '10', '20', '55',
       '40'], dtype=object)

In [317]:
df['Duration_Hour'] = df['Duration_Hour'].replace('5m', 0)
df['Duration_Minutes'] = df['Duration_Minutes'].replace(np.nan, 0)

In [318]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  object
 1   Source            10683 non-null  object
 2   Destination       10683 non-null  object
 3   Dep_Time          10683 non-null  object
 4   Duration          10683 non-null  object
 5   Total_Stops       10683 non-null  int64
 6   Additional_Info   10683 non-null  object
 7   Price             10683 non-null  int64
 8   Date              10683 non-null  int64
 9   Month             10683 non-null  int64
 10  Year              10683 non-null  int64
 11  Arrival_Hour      10683 non-null  int64
 12  Arrival_Minutes   10683 non-null  int64
 13  Duration_Hour     10683 non-null  object
 14  Duration_Minutes  10683 non-null  object
dtypes: int64(7), object(8)
memory usage: 1.2+ MB

In [319]:
df['Duration_Hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', 0, '41', '40'], dtype=object)

In [320]:
df.head()

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Duration_Hour,Duration_Minutes
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,0,No info,3897,24,3,2019,1,10,2,50
1,Air India,Kolkata,Banglore,05:50,7h 25m,2,No info,7662,1,5,2019,13,15,7,25
2,Jet Airways,Delhi,Cochin,09:25,19h,2,No info,13882,9,6,2019,4,25,19,0
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1,No info,6218,12,5,2019,23,30,5,25
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1,No info,13302,1,3,2019,21,35,4,45

In [321]:
df['Duration_Hour'] = df['Duration_Hour'].astype(int)
df['Duration_Minutes'] = df['Duration_Minutes'].astype(int)

In [322]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  object
 1   Source            10683 non-null  object
 2   Destination       10683 non-null  object
 3   Dep_Time          10683 non-null  object
 4   Duration          10683 non-null  object
 5   Total_Stops       10683 non-null  int64
 6   Additional_Info   10683 non-null  object
 7   Price             10683 non-null  int64
 8   Date              10683 non-null  int64
 9   Month             10683 non-null  int64
 10  Year              10683 non-null  int64
 11  Arrival_Hour      10683 non-null  int64
 12  Arrival_Minutes   10683 non-null  int64
 13  Duration_Hour     10683 non-null  int64
 14  Duration_Minutes  10683 non-null  int64
dtypes: int64(9), object(6)
memory usage: 1.2+ MB

In [323]:
df.drop('Duration', axis=1, inplace= True )

In [324]:
df.head()

,Airline,Source,Destination,Dep_Time,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Duration_Hour,Duration_Minutes
0,IndiGo,Banglore,New Delhi,22:20,0,No info,3897,24,3,2019,1,10,2,50
1,Air India,Kolkata,Banglore,05:50,2,No info,7662,1,5,2019,13,15,7,25
2,Jet Airways,Delhi,Cochin,09:25,2,No info,13882,9,6,2019,4,25,19,0
3,IndiGo,Kolkata,Banglore,18:05,1,No info,6218,12,5,2019,23,30,5,25
4,IndiGo,Banglore,New Delhi,16:50,1,No info,13302,1,3,2019,21,35,4,45

In [325]:
from sklearn.preprocessing import OrdinalEncoder

In [326]:
encoder = OrdinalEncoder()

In [327]:
encoded = encoder.fit_transform(df[['Airline', 'Source', 'Destination', 'Additional_Info']])

In [328]:
encoded

array([[ 3.,  0.,  5.,  8.],
       [ 1.,  3.,  0.,  8.],
       [ 4.,  2.,  1.,  8.],
       ...,
       [ 4.,  0.,  2.,  8.],
       [10.,  0.,  5.,  8.],
       [ 1.,  2.,  1.,  8.]], shape=(10683, 4))

In [329]:
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [330]:
encoded_df

       Airline  Source  Destination  Additional_Info
0          3.0     0.0          5.0              8.0
1          1.0     3.0          0.0              8.0
2          4.0     2.0          1.0              8.0
3          3.0     3.0          0.0              8.0
4          3.0     0.0          5.0              8.0
...        ...     ...          ...              ...
10678      0.0     3.0          0.0              8.0
10679      1.0     3.0          0.0              8.0
10680      4.0     0.0          2.0              8.0
10681     10.0     0.0          5.0              8.0
10682      1.0     2.0          1.0              8.0

[10683 rows x 4 columns]

In [331]:
df.drop(['Airline', 'Source', 'Destination', 'Additional_Info'], axis=1, inplace=True)

In [332]:
final_df = pd.concat([encoded_df, df], axis=1)

In [333]:
final_df.head()

,Airline,Source,Destination,Additional_Info,Dep_Time,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Duration_Hour,Duration_Minutes
0,3.0,0.0,5.0,8.0,22:20,0,3897,24,3,2019,1,10,2,50
1,1.0,3.0,0.0,8.0,05:50,2,7662,1,5,2019,13,15,7,25
2,4.0,2.0,1.0,8.0,09:25,2,13882,9,6,2019,4,25,19,0
3,3.0,3.0,0.0,8.0,18:05,1,6218,12,5,2019,23,30,5,25
4,3.0,0.0,5.0,8.0,16:50,1,13302,1,3,2019,21,35,4,45

In [334]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  float64
 1   Source            10683 non-null  float64
 2   Destination       10683 non-null  float64
 3   Additional_Info   10683 non-null  float64
 4   Dep_Time          10683 non-null  object
 5   Total_Stops       10683 non-null  int64
 6   Price             10683 non-null  int64
 7   Date              10683 non-null  int64
 8   Month             10683 non-null  int64
 9   Year              10683 non-null  int64
 10  Arrival_Hour      10683 non-null  int64
 11  Arrival_Minutes   10683 non-null  int64
 12  Duration_Hour     10683 non-null  int64
 13  Duration_Minutes  10683 non-null  int64
dtypes: float64(4), int64(9), object(1)
memory usage: 1.1+ MB

In [335]:
final_df['Departure_Hour'] = final_df['Dep_Time'].str.split(':').str[0]
final_df['Departure_Minutes'] = final_df['Dep_Time'].str.split(':').str[1]
final_df['Departure_Hour'] = final_df['Departure_Hour'].astype(int)
final_df['Departure_Minutes'] = final_df['Departure_Minutes'].astype(int)
final_df.drop('Dep_Time', axis=1, inplace=True)

In [336]:
final_df

,Airline,Source,Destination,Additional_Info,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Duration_Hour,Duration_Minutes,Departure_Hour,Departure_Minutes
0,3.0,0.0,5.0,8.0,0,3897,24,3,2019,1,10,2,50,22,20
1,1.0,3.0,0.0,8.0,2,7662,1,5,2019,13,15,7,25,5,50
2,4.0,2.0,1.0,8.0,2,13882,9,6,2019,4,25,19,0,9,25
3,3.0,3.0,0.0,8.0,1,6218,12,5,2019,23,30,5,25,18,5
4,3.0,0.0,5.0,8.0,1,13302,1,3,2019,21,35,4,45,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0.0,3.0,0.0,8.0,0,4107,9,4,2019,22,25,2,30,19,55
10679,1.0,3.0,0.0,8.0,0,4145,27,4,2019,23,20,2,35,20,45
10680,4.0,0.0,2.0,8.0,0,7229,27,4,2019,11,20,3,0,8,20
10681,10.0,0.0,5.0,8.0,0,12648,1,3,2019,14,10,2,40,11,30
10682,1.0,2.0,1.0,8.0,2,11753,9,5,2019,19,15,8,20,10,55

In [337]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dep_Time          10683 non-null  object
 1   Total_Stops       10683 non-null  int64
 2   Price             10683 non-null  int64
 3   Date              10683 non-null  int64
 4   Month             10683 non-null  int64
 5   Year              10683 non-null  int64
 6   Arrival_Hour      10683 non-null  int64
 7   Arrival_Minutes   10683 non-null  int64
 8   Duration_Hour     10683 non-null  int64
 9   Duration_Minutes  10683 non-null  int64
dtypes: int64(9), object(1)
memory usage: 834.7+ KB

In [338]:
final_df

,Airline,Source,Destination,Additional_Info,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Duration_Hour,Duration_Minutes,Departure_Hour,Departure_Minutes
0,3.0,0.0,5.0,8.0,0,3897,24,3,2019,1,10,2,50,22,20
1,1.0,3.0,0.0,8.0,2,7662,1,5,2019,13,15,7,25,5,50
2,4.0,2.0,1.0,8.0,2,13882,9,6,2019,4,25,19,0,9,25
3,3.0,3.0,0.0,8.0,1,6218,12,5,2019,23,30,5,25,18,5
4,3.0,0.0,5.0,8.0,1,13302,1,3,2019,21,35,4,45,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0.0,3.0,0.0,8.0,0,4107,9,4,2019,22,25,2,30,19,55
10679,1.0,3.0,0.0,8.0,0,4145,27,4,2019,23,20,2,35,20,45
10680,4.0,0.0,2.0,8.0,0,7229,27,4,2019,11,20,3,0,8,20
10681,10.0,0.0,5.0,8.0,0,12648,1,3,2019,14,10,2,40,11,30
10682,1.0,2.0,1.0,8.0,2,11753,9,5,2019,19,15,8,20,10,55

In [339]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [340]:
X = final_df[['Airline', 'Total_Stops', 'Arrival_Hour', 'Arrival_Minutes', 'Departure_Hour', 'Departure_Minutes', 'Duration_Hour', 'Duration_Minutes']]
y = final_df[['Price']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [343]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
model = RandomForestRegressor(
    n_estimators=500,
    max_depth=15,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)  # ← missing this
y_pred = model.predict(X_test)  # ← missing this

c:\Users\Ekangsh\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\Ekangsh\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [344]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

MAE: 1713.7238792919718
RMSE: 2993.6714767441026
R2: 0.5765411413393406

In [345]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Airline            10683 non-null  float64
 1   Source             10683 non-null  float64
 2   Destination        10683 non-null  float64
 3   Additional_Info    10683 non-null  float64
 4   Total_Stops        10683 non-null  int64
 5   Price              10683 non-null  int64
 6   Date               10683 non-null  int64
 7   Month              10683 non-null  int64
 8   Year               10683 non-null  int64
 9   Arrival_Hour       10683 non-null  int64
 10  Arrival_Minutes    10683 non-null  int64
 11  Duration_Hour      10683 non-null  int64
 12  Duration_Minutes   10683 non-null  int64
 13  Departure_Hour     10683 non-null  int64
 14  Departure_Minutes  10683 non-null  int64
dtypes: float64(4), int64(11)
memory usage: 1.2 MB